name: Desplegar sitio web en GH pages

on: 
    push:
        branches:
            -main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Hacer checkout del repositorio
              uses: actions/checkout@v3

            - name: Configurar node
              uses: action/setup-node@3
              with: 
                node-version: 18
            - run: npm install
            - run: npm test

            - name: Desplegar en GH Pages
              uses: peaceiris/action-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./
                allow_empty_commit: true